options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'python:3.12-slim'
    entrypoint: bash
    args: ['-c', 'pip install -r requirements.txt && pytest test_app.py -v']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cicd-rag-repo/movie-rag-job', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cicd-rag-repo/movie-rag-job']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'movie-rag-job'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cicd-rag-repo/movie-rag-job'
      - '--region=us-central1'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - 'movie-rag-job'
      - '--region=us-central1'
      - '--wait'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cicd-rag-repo/movie-rag-job'

